// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkQXU6xtKlzF0GcUCdSGRcYROkoUsclF0',
    appId: '1:1083924034933:web:35f67d3e3aef41398c4f3c',
    messagingSenderId: '1083924034933',
    projectId: 'crud-ab74f',
    authDomain: 'crud-ab74f.firebaseapp.com',
    storageBucket: 'crud-ab74f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLjQDTZHZp1uEir8OmSGKA10R3MaQdl54',
    appId: '1:1083924034933:android:46fc5580b957dee48c4f3c',
    messagingSenderId: '1083924034933',
    projectId: 'crud-ab74f',
    storageBucket: 'crud-ab74f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr7Ak75niy6ssMKQO5gWmWUpouAemNIUY',
    appId: '1:1083924034933:ios:c8b5d2ade7489bbd8c4f3c',
    messagingSenderId: '1083924034933',
    projectId: 'crud-ab74f',
    storageBucket: 'crud-ab74f.firebasestorage.app',
    iosBundleId: 'com.example.firebasecrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr7Ak75niy6ssMKQO5gWmWUpouAemNIUY',
    appId: '1:1083924034933:ios:c8b5d2ade7489bbd8c4f3c',
    messagingSenderId: '1083924034933',
    projectId: 'crud-ab74f',
    storageBucket: 'crud-ab74f.firebasestorage.app',
    iosBundleId: 'com.example.firebasecrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkQXU6xtKlzF0GcUCdSGRcYROkoUsclF0',
    appId: '1:1083924034933:web:7608593385793f808c4f3c',
    messagingSenderId: '1083924034933',
    projectId: 'crud-ab74f',
    authDomain: 'crud-ab74f.firebaseapp.com',
    storageBucket: 'crud-ab74f.firebasestorage.app',
  );
}
